LiqunManagement/Controllers/FormController.cs
using LiqunManagement.Attributes;
using LiqunManagement.Models;
using LiqunManagement.Services;
using LiqunManagement.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using NPOI.Util;


namespace LiqunManagement.Controllers
{
    [AdminAuthorize]
    public class FormController : BaseController
    {
        DDLServices ddlservices = new DDLServices();

        // Initial Model
        public FormViewModels InitialModel()
        {
            var model = new FormViewModels
            {
                FormID = null,
                CaseID = null,
                homeobjectviewmodel = null,
            };
            return model;
        }

        #region 房屋物件資料
        [HttpGet]
        public ActionResult HomeObject(string CaseID, string ControllerName)
        {

            //若初次進入頁面，則FormID、CaseID皆為null
            var FormID = CaseID != null ? formdb.HomeObject.Where(x => x.CaseID == CaseID).Select(x => x.FormID).FirstOrDefault() : null;
            DDLServices ddlservices = new DDLServices();
            var initmodel = InitialModel();
            ControllerName = ControllerName != null ? "Secretary" : "Sales";     //是否秘書端進入
            ViewBag.ControllerName = ControllerName;
            logger.Info("進入房屋物件資料頁面，ControllerName:" + ControllerName);
            #region 使用者資料
            var EmployeeData = (from db in memberdb.Members.Where(x => x.Account == User.Identity.Name)
                                join empdb in memberdb.EmployeeData on db.Account equals empdb.Account into temp
                                from empdb0 in temp.DefaultIfEmpty()
                                join deptdb in memberdb.Department on empdb0.DivCode equals deptdb.DivCode into temp2
                                from deptdb0 in temp2.DefaultIfEmpty()
                                select new MembersViewModel
                                {
                                    Name = db.Name,
                                    Department = empdb0 != null ? deptdb0.DivFullName : null,
                                    Position = empdb0 != null ? empdb0.JobTitle : null,
                                }).FirstOrDefault();
            if (EmployeeData != null)
            {
                ViewBag.UserName = EmployeeData.Name;                 //使用者名稱
                ViewBag.Department = EmployeeData.Department;   //使用者部門
                ViewBag.Position = EmployeeData.Position;       //使用者職位
            }
            //確認角色
            var IsAdmin = User.IsInRole("Admin");
            ViewBag.Role = User.IsInRole("Admin") ? "Admin" : User.IsInRole("Agent") ? "Agent" : User.IsInRole("Secretary") ? "Secretary" : "";
            #endregion

            #region 下拉選單
            //縣市地址
            ViewBag.citylist = JsonConvert.SerializeObject(ddlservices.GetRegionDDL("").ddllist.ToList());
            //付款日
            List<int> payment_date = new List<int>();
            for (int i = 1; i <= 31; i++){payment_date.Add(i);}
            ViewBag.Payment_date = payment_date;

            ViewBag.phaselist = JsonConvert.SerializeObject(ddlservices.GetPhaseDDL("").ddllist.ToList());
            #endregion

            if (!String.IsNullOrEmpty(FormID))
            {
                #region 存在表單資料
                try
                {
                    var CaseData = formdb.ObjectForm.Where(x => x.FormID == FormID).FirstOrDefault();
                    if (CaseData.ProcessAccount != User.Identity.Name && !IsAdmin)
                    {
                        ///無編輯權限: 
                        ///非處理職員 且 非系統管理員
                        return RedirectToAction("CaseManage", ControllerName);
                    }
                    var ExistHomeObject = formdb.HomeObject.Where(x => x.FormID == CaseID).FirstOrDefault();
                    if (ExistHomeObject != null)
                    {
                        //取得物件地址DDL
                        var addressdata = formdb.Region.Where(x => x.City == ExistHomeObject.city && x.District == ExistHomeObject.district && x.Road == ExistHomeObject.road).FirstOrDefault();
                        var CityCode = addressdata != null ? addressdata.CityCode : "";
                        var DistrictCode = addressdata != null ? addressdata.DistrictCode : "";
                        var Address = addressdata != null ? addressdata.RoadCode : "";
                        var districtlist = addressdata != null ? JsonConvert.SerializeObject(ddlservices.GetRegionDDL(CityCode).ddllist.ToList()) : "";
                        var roadlist = addressdata != null ? JsonConvert.SerializeObject(ddlservices.GetRegionDDL(DistrictCode).ddllist.ToList()) : "";

                        var FormValue = new HomeObjectViewModel
                        {
                            Phase = ExistHomeObject.Phase.ToString(),
                            objecttype = ExistHomeObject.objecttype,
                            notarization = ExistHomeObject.notarization,
                            notarizationTime = Convert.ToDateTime(ExistHomeObject.signdate),
                            signdateStr = Convert.ToDateTime(ExistHomeObject.signdate).ToString("yyyy-MM-dd"),
                            appraiser = ExistHomeObject.appraiser,
                            feature = ExistHomeObject.feature != null ? ExistHomeObject.feature : "",
                            citycode = CityCode,
                            districtcode = DistrictCode,
                            distirctJsonDDL = districtlist,     //鄉鎮市區地址
                            roadcode = Address,
                            roadJsonDDL = roadlist,             //道路地址
                            AddressDetail = ExistHomeObject.detailaddress,
                            usefor = ExistHomeObject.usefor,
                            useforelse = String.IsNullOrWhiteSpace(ExistHomeObject.useforelse) ? "" : ExistHomeObject.useforelse,
                            rent = ExistHomeObject.rent,
                            deposit = ExistHomeObject.deposit,
                            management_fee = ExistHomeObject.management_fee,
                            startdateStr = Convert.ToDateTime(ExistHomeObject.startdate).ToString("yyyy-MM-dd"),
                            enddateStr = Convert.ToDateTime(ExistHomeObject.enddate).ToString("yyyy-MM-dd"),
                            paydate = ExistHomeObject.paydate,
                            buildtype = ExistHomeObject.buildtype,
                            roomtype = ExistHomeObject.roomtype,
                            roomamount = ExistHomeObject.roomamount != null ? ExistHomeObject.roomamount : "",
                            //roomamountlist = JsonConvert.DeserializeObject<List<int>>(ExistHomeObject.roomamount),
                            havepark = ExistHomeObject.havepark != null ? ExistHomeObject.havepark : "",
                            //haveparklist = JsonConvert.DeserializeObject<List<int>>(ExistHomeObject.havepark),
                            parktype = ExistHomeObject.parktype != null ? ExistHomeObject.parktype : 0,
                            parkfloor = ExistHomeObject.parkfloor != null ? ExistHomeObject.parkfloor : "",
                            //parkfloorlist = JsonConvert.DeserializeObject<List<int>>(ExistHomeObject.parkfloor),
                            carpositionnumber = String.IsNullOrEmpty(ExistHomeObject.carpositionnumber) ? "" : ExistHomeObject.carpositionnumber,   //汽車位編號
                            carmonthrent = ExistHomeObject.carmonthrent != null ? ExistHomeObject.carmonthrent : 0,
                            carparkmanagefee = ExistHomeObject.carparkmanagefee != null ? ExistHomeObject.carparkmanagefee : 0,
                            scooterparkfloor = ExistHomeObject.scooterparkfloor != null ? ExistHomeObject.scooterparkfloor : "",
                            //scooterparkfloorlist = JsonConvert.DeserializeObject<List<int>>(ExistHomeObject.scooterparkfloor),
                            scooterpositionnumber = String.IsNullOrEmpty(ExistHomeObject.scooterpositionnumber) ? "" : ExistHomeObject.scooterpositionnumber,   //機車位編號
                            scootermonthrent = ExistHomeObject.scootermonthrent != null ? ExistHomeObject.scootermonthrent : 0,
                            scootermanagefee = ExistHomeObject.scootermanagefee != null ? ExistHomeObject.scootermanagefee : 0,
                            Accessory = ExistHomeObject.Accessory != null ? ExistHomeObject.Accessory : "",    //房屋附屬物件

                            Memo = String.IsNullOrEmpty(ExistHomeObject.Memo) ? "" : ExistHomeObject.Memo.Replace("\r\n", "\\r\\n"),
                        };

                        var model = new FormViewModels
                        {
                            FormID = FormID != null ? FormID : "",
                            CaseID = CaseID != null ? CaseID : "",
                            homeobjectviewmodel = FormValue,
                        };

                        ViewBag.FileNameList = ExistHomeObject.taxfile_name != null ? JsonConvert.DeserializeObject<List<string>>(ExistHomeObject.taxfile_name) : null;
                        ViewBag.FileAliasList = ExistHomeObject.taxfile_alias != null ?JsonConvert.DeserializeObject<List<string>>(ExistHomeObject.taxfile_alias) : null;

                        return View(model);
                    }
                }
                catch (Exception ex)
                {
                    logger.Error("取得房屋物件資料錯誤 : " + ex.ToString());
                }
                #endregion
            }

            //若無案件編號; 無物件資料
            //返回空白表單
            return View(initmodel);
        }

        //[Insert]新增物件
        [HttpPost]
        public ActionResult HomeObject(HomeObjectInputViewModel inputmodel, string ControllerName)
        {

LiqunManagement/Views/Sales/CaseProcess.cshtml
@model LiqunManagement.ViewModels.FormViewModels
@{
    ViewBag.Title = "案件管理";
    ViewBag.Controller = "Case";
    ViewBag.Branches = "CaseProcess";
    Layout = "~/Views/Shared/smartadmin_Layout.cshtml";
}
<link href="~/Content/smartadmin-package-4.5.1/smartadmin-html-full/dist/css/datagrid/datatables/datatables.bundle.css" rel="stylesheet" />
<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item">
            <a href="javascript:void(0);">後臺管理系統</a>
        </li>
        <li class="breadcrumb-item">業務區</li>
        <li class="breadcrumb-item active">案件管理</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block">
            <span class="js-get-date">Monday, June 12, 2023</span>
        </li>
    </ol>
    <div class="row">
        <div class="col-lg-12 sortable-grid ui-sortable">

            <div id="panel-4" class="panel panel-sortable panel-locked" data-panel-lock="false" data-panel-close="false" data-panel-fullscreen="false" data-panel-collapsed="false" data-panel-color="false" data-panel-locked="false" data-panel-refresh="false" data-panel-reset="false">
                <div class="panel-hdr" role="heading">
                    <h2 class="ui-sortable-handle">
                        Sale
                        <span class="fw-300"><i>Records</i></span>
                    </h2>
                </div>
                <div class="panel-container show">
                    <div class="loader">
                        <i class="fal fa-spinner-third fa-spin-4x fs-xxl"></i>
                    </div>
                    <div class="panel-content">
                        <div id="dt-basic-example_wrapper" class="dataTables_wrapper dt-bootstrap4">
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="dt-basic-example" class="table table-bordered table-hover table-striped w-100 dataTable dtr-inline collapsed" role="grid" aria-describedby="dt-basic-example_info" style="width: 876px;">
                                        <thead class="bg-fusion-600">
                                            <tr role="row">
                                                <th class="sorting_asc" tabindex="0" aria-controls="dt-basic-example" rowspan="1" colspan="1" style="width: 76.2px;" aria-sort="ascending" aria-label="CustomerID: activate to sort column descending">表單編號</th>
                                                <th class="sorting" tabindex="0" aria-controls="dt-basic-example" aria-label="Name: activate to sort column ascending">表單處理人員</th>
                                                <th class="sorting" tabindex="0" aria-controls="dt-basic-example" aria-label="CustomerEmail: activate to sort column ascending">物件地址</th>
                                                <th class="sorting" tabindex="0" aria-controls="dt-basic-example" aria-label="CustomerCVV: activate to sort column ascending">簽約日</th>
                                                <th class="sorting" tabindex="0" aria-controls="dt-basic-example" aria-label="Country: activate to sort column ascending">房東姓名</th>
                                                <th class="sorting" tabindex="0" aria-controls="dt-basic-example" aria-label="InvoiceAmount: activate to sort column ascending">房客姓名</th>
                                                <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 0px;" aria-label=""></th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @if (Model.objectformlist != null)
                                            {
                                                if (Model.objectformlist.Count() > 0)
                                                {
                                                    foreach (var item in Model.objectformlist)
                                                    {
                                                        <tr role="row" class="odd">
                                                            <td class="sorting_1 dtr-control">@item.FormID</td>
                                                            <td>@item.ProcessName</td>
                                                            <td>@item.Address</td>
                                                            <td>@item.SignDate.AddYears(-1911).ToString("yyy年MM月dd日")</td>
                                                            <td style="display: none;">@item.Landlord</td>
                                                            <td style="display: none;">@item.Tenant</td>

                                                            <td style="display: none;">
                                                                <div class="dropdown d-inline-block dropleft">
                                                                    <a href="#" class="btn btn-sm btn-icon btn-outline-primary rounded-circle shadow-0" data-toggle="dropdown" aria-expanded="true" title="More options">
                                                                        <i class="fal fa-ellipsis-v"></i>
                                                                    </a>
                                                                    <div class="dropdown-menu">
                                                                        <a class="dropdown-item" href="@Url.Action("ReadForm", "Form", new { CaseID = item.CaseID, ControllerName = "Sales"})" target="_blank">表單閱覽</a>
                                                                        <a class="dropdown-item" href="@Url.Action("Uploads", "Form", new { FormID = item.FormID, ControllerName = "Sales"})">附件上傳</a>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    }
                                                }
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <!-- datatable end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

@section scripts
{
    <script src="~/Content/smartadmin-package-4.5.1/smartadmin-html-full/dist/js/datagrid/datatables/datatables.bundle.js"></script>
    <script>
        $(document).ready(function () {

            /* init datatables */
            $('#dt-basic-example').dataTable(
                {
                    //響應式設計
                    "pageLength": 100,
                    responsive: true,
                    //定義工具欄和元素的布局結構
                    dom: "<'row mb-3'<'col-sm-12 col-md-6 d-flex align-items-center justify-content-start'f><'col-sm-12 col-md-6 d-flex align-items-center justify-content-end'B>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
                    //定義按鈕
                    buttons: [
                        {
                            extend: 'colvis',
                            text: '觀看欄位',
                            titleAttr: 'Col visibility',
                            className: 'btn-outline-default'
                        },
                        //{
                        //    extend: 'csvHtml5',
                        //    text: 'CSV',
                        //    titleAttr: 'Generate CSV',
                        //    className: 'btn-outline-default'
                        //},
                        {
                            extend: 'copyHtml5',
                            text: 'Copy',
                            titleAttr: 'Copy to clipboard',
                            className: 'btn-outline-default'
                        },
                        {
                            extend: 'print',
                            text: '<i class="fal fa-print"></i>',
                            titleAttr: 'Print Table',
                            className: 'btn-outline-default'
                        }

                    ],
                    //定義每列的屬性和操作
                    //columnDefs: [
                    //    {
                    //        //目標列為倒數第一列
                    //        targets: -1,
                    //        //空的標題
                    //        title: '',
                    //        //不可排序
                    //        orderable: false,
                    //        //自定義內容
                    //        ///在渲染函數中，通過字符串產生了一段HTML碼，其中包刮"刪除"和"更多選項"的按鈕，
                    //        ///刪除按鈕允許用戶刪除紀錄，更多選項按鈕則打開一個下拉選單，其中包含一些額外的操作選項，如更換狀態和生成報告
                    //        render: function (data, type, full, meta) {


                    //            //-- ES6
                    //            //-- convert using https://babeljs.io online transpiler
                    //            return `
                    //            <a href='javascript:void(0);' class='btn btn-sm btn-icon btn-outline-danger rounded-circle mr-1' title='Delete Record'>
                    //                <i class="fal fa-times"></i>
                    //            </a>
                    //            <div class='dropdown d-inline-block dropleft '>
                    //                <a href='#'' class='btn btn-sm btn-icon btn-outline-primary rounded-circle shadow-0' data-toggle='dropdown' aria-expanded='true' title='More options'>
                    //                    <i class="fal fa-ellipsis-v"></i>
                    //                </a>
                    //                <div class='dropdown-menu'>
                    //                    <a class='dropdown-item' href='javascript:void(0);'>編輯表單</a>
                    //                    <a class='dropdown-item' href='javascript:void(0);'>匯出Word表單</a>
                    //                </div>
                    //            </div>`;

                    //            //ES5 example below:


                    //            //return "\n\t\t\t\t\t\t<a href='javascript:void(0);' class='btn btn-sm btn-icon btn-outline-danger rounded-circle mr-1' title='Delete Record'>\n\t\t\t\t\t\t\t<i class=\"fal fa-times\"></i>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t\t<div class='dropdown d-inline-block dropleft'>\n\t\t\t\t\t\t\t<a href='#'' class='btn btn-sm btn-icon btn-outline-primary rounded-circle shadow-0' data-toggle='dropdown' aria-expanded='true' title='More options'>\n\t\t\t\t\t\t\t\t<i class=\"fal fa-ellipsis-v\"></i>\n\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t<div class='dropdown-menu'>\n\t\t\t\t\t\t\t\t<a class='dropdown-item' href='javascript:void(0);'>編輯表單</a>\n\t\t\t\t\t\t\t\t<a class='dropdown-item' href='javascript:void(0);'>匯出Word表單</a>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t</div>";
                    //        },
                    //    },

                    //]

                });
        });

        function submit(FormID) {
            console.log('%c' + FormID, 'color: orange; font-size:24px');
            if (confirm('確認將案件 : ' + FormID + ' 提交至秘書處理?')) {
                $.ajax({
                    type: "POST",
                    data: { FormID: FormID },
                    url: '@Url.Content("~/Sales/CaseManage")',
                }).done(function (result){
                    if (result == 'successed') {
                        if (confirm(result)) {
                            location.reload();
                        };
                    };
                });
            }
            return;
        }
    </script>
}